### ISSUE TITLE
Request to Add Pop!_OS to the List of Distributions

### ISSUE THREAD

**Issue by iAnonymous3000** [eylenburg/eylenburg.github.io#22]
Name of Distribution: Pop!_OS
Base: Ubuntu
Reason for Inclusion: Pop!_OS is gaining popularity, especially among users who prefer a clean and focused desktop experience. It provides excellent gaming, professional graphics, and software development support, making it a valuable addition to any comprehensive and up-to-date list.

By adding Pop!_OS to our list, we acknowledge its growing relevance and provide better support for users of Pop!_OS. This will help them feel more comfortable using our project, knowing their system is fully supported.

Thank you for considering this addition.

**Comment by eylenburg** [comment]
I decided to only include "original" distros rather than forks, because the differences are quite superficial (normally just limited to the default desktop environment and maybe a different installer). For that reason I even removed Mint, because most rows were identical with Ubuntu.

Ubuntu, SLE and RHEL are the only "forks" I'll keep because of their commercial relevance and because they "sponsor" the upstream (like Red Hat sponsoring Fedora and owning their trademark)
