### ISSUE TITLE
Consider changing information about Google Play Services/FOSS

### ISSUE THREAD

**Issue by Neebly** [eylenburg/eylenburg.github.io#23]
Greetings.

Almost all systems has the info "Yes, but executes proprietary code" but this information could be inaccurate depending on the OS.

I would change with the following:

GrapheneOS -> No, but the compatibility layer is open source.
The binaries are completely closed-source so saying they are open-source is innacurate, in my opinion.

DivestOS, CalyxOS, IodéOS and /e/ -> Yes, but executes propietary code from the apps.

**Comment by Neebly** [comment]
> The implementation it's elaborating on for GrapheneOS is GmsCompat, which is of course fully open source.
But not the binaries.
When using sandboxed Play Store you are running closed-source binaries.
MicroG is open-source but may allow apps to execute propietary libraries and even download more closed-source stuff.

I think this is worth mentioning.

**Comment by eylenburg** [comment]
Maybe my comparison is incorrect but could you compare to these ways to run Windows app on Linux?

MicroG is like running Wine. It's not 100% compatible, it's a reverse engineered FOSS compatibility layer. But while it's FOSS, you still use it to run proprietary Windows apps and often have to load original Microsoft DLLs and other Microsoft components like .NET to actually be able to run these apps.

GmsCompat is like running KVM, with a Windows VM on top. (The Windows VM is the equivalent to the Play Services.) You run the original, proprietary software (Windows), though in a sandbox (VM), and that makes it almost 100% compatible to Windows apps, but it's a thinner FOSS layer overall (just KVM / GmsCompat).

Maybe it's actually best to delete this whole row because it's a bit pointless and not straight-forward. Or do I agree that MicroG "seems" a bit more open source intuitively but it's questionable whether actually means anything in the end.

**Comment by Neebly** [comment]
> Maybe my comparison is incorrect but could you compare to these ways to run Windows app on Linux?
> 
> MicroG is like running Wine. It's not 100% compatible, it's a reverse engineered FOSS compatibility layer. But while it's FOSS, you still use it to run proprietary Windows apps and often have to load original Microsoft DLLs and other Microsoft components like .NET to actually be able to run these apps.
> 
> GmsCompat is like running KVM, with a Windows VM on top. (The Windows VM is the equivalent to the Play Services.) You run the original, proprietary software (Windows), though in a sandbox (VM), and that makes it almost 100% compatible to Windows apps, but it's a thinner FOSS layer overall (just KVM / GmsCompat).
> 
> Maybe it's actually best to delete this whole row because it's a bit pointless and not straight-forward. Or do I agree that MicroG "seems" a bit more open source intuitively but it's questionable whether actually means anything in the end.

What you say makes much sense.
And maybe, the comparison I wrote wasn't accurate.

On the other hand, we can reasonably say that when we install proprietary applications on these alternatives, both have similar problems.
However, if we focus on both Google Play Services alternatives, we could sum up saying that one is fully FOSS (MicroG) but not the other (GmsCompat+sandboxed Play Services) The first one is available in a well-known opensource channel like F-Droid but not the second.

And this is what I wanted to express. That this possibility from GrapheneOS appears as FOSS is, in my view, inadequate.

Anyway, thank you for not just closing the issue and letting me debate with you on this issue in such a cordial way
