### ISSUE TITLE
Error with Brave browser

### ISSUE THREAD

**Issue by I-I-IT** [eylenburg/eylenburg.github.io#24]
Brave browser supports Encrypted Client Hello (ECH) by default. Source : privacytests.org, my own testing using defo.ie/ech-check.php

**Comment by eylenburg** [comment]
Privacytests.org says that all Chromium browser (except somehow Opera) have "ECH enabled", and that Firefox doesn't. That's a bit strange because Firefox being the first browser to support for ECH was in the news recently.

Wikipedia says that Firefox (desktop only) has it enabled by default and Chrome (presumably all Chromium browsers) behind a flag: https://en.wikipedia.org/wiki/Server_Name_Indication#Support - this is what I got in my table for now.

I couldn't find any more info on Brave except that there is a flag for ECH, but as far as I know it's not yet on by default or exposed in the normal settings?
