### ISSUE TITLE
Android: "Network-based location" vs "Network location provider" and other location functionality

### ISSUE THREAD

**Issue by alohapersona** [eylenburg/eylenburg.github.io#70]
There is two entries that are somewhat related, but not exactly the same. I think there's been some mixing of them.
- "Network-based location" should be about the functionality to locate based on Wi-Fi, Bluetooth and/or mobile networks. In other terms, it's a feature to provide geolocation in scenarios where GNSS typically do not work (well), e.g. indoors, or where one wants to avoid it's battery consumption (which is typically significantly higher than network-based). GrapheneOS Emulated network location provider does **not** provide this functionality. DivestOS can provide it when installing microG and LineageOS can provide it when installing microG or Play Services.
- "Network location provider" should be about the OS providing a ["network" location provider](https://developer.android.com/reference/android/location/LocationManager#NETWORK_PROVIDER) to installed apps. Which means that if an app requests a location from the network provider from the OS (and not the GPS provider that uses GNSS), there will be replies. This is probably what GrapheneOS Emulated network location provider can do, but I'm not sure it will be redirected to Google when using Sandboxed Play Services (should be easy to confirm with the SatStat app, that allows to display the GPS and network provider on a map for comparison). LineageOS should be able to provide this with both microG and Play Services and also Qualcomm NLP on some devices, I am not sure if DivestOS can.
- There could be two additional location related functionality that could be considered in the comparison:
  - ["fused" location provider](https://developer.android.com/reference/android/location/LocationManager#FUSED_PROVIDER) support: It's supported by Play Services, but not microG, but also requires the OS to support it. Some OS ship with a broken fused location provider (see https://github.com/organicmaps/organicmaps/issues/4158#issuecomment-1519019882).
  - [Google Fused Location Provider API](https://developers.google.com/location-context/fused-location-provider/) support: This can be provided through Play Services, microG and also there is a feature in GrapheneOS to emulate it when Sandboxed Play Services is installed (but only then, as apps would not try to use this API if they don't detect Play Services installed).

**Comment by eylenburg** [comment]
Hi, thank you for the issue. 

On the row "network-based location" in "features", I think it's correct as it. DivestOS doesn't support it even with microG (["Enabling the location provider in microG/UnifiedNlp will not do anything as it does not have permission to be a system location provider."](https://divestos.org/pages/faq)). You're right about Graphene's GNSS redirect not really offering a network-based location (e.g. when indoors) but it's still possible with the optional Play Services. So I think the green colour can stay, to be consistent with the other ROMs that have (optional) network-based location via microG. But I think it's worthwhile elaborating a bit more on the limits of the GNSS redirect.

I might just rename the other row to "provider for network-based location" because this in the "Degoogling" sub-table. But you actually made me think about the appropriate colour for GrapheneOS. "Emulated/GNSS,or Google" is basically the same as "None, or Google", which I've marked light green in other cells (e.g. SUPL for /e/OS). So perhaps it should be light green for GrapheneOS as well - it is fully degoogled by default but a bit more limited in functionality (e.g. as you mentioned, GNSS wouldn't work when you're indoors).

Is Fused Location something combining the data from GNSS and a network-based location to get the best mix of accuracy and battery use? It might be worth adding, at least in a single row, with support for Stock Android and GrapheneOS with Play Services.

**Comment by alohapersona** [comment]
Regarding DivestOS FAQ: Enabling location in microG will not allow using the "network" location provider, however it will provide network-based locations when accessed through the Google Fused Location Provider API implementation in microG. For example, if you used Google Maps (which uses Google Fused Location API) on DivestOS with microG it could get network-based indoor location. So the the FAQ in DivestOS is not wrong, but also not completely true when taking all possible ways to get network location into the picture.

Regarding Emulated network location provider in GrapheneOS: The solution of GrapheneOS helps with a lot of apps, because most apps that request network location are not particularly interested in ensuring that they get indoor locations, but rather care about not consuming additional battery, as GNSS is typically battery intensive. A traditional example is weather apps, which fetch your approximate location in the background every hour so they can warn you of rain at your location. As they request in the background every hour, it would be bad if they consumed a lot of energy for doing so, so restricting to network location is a good idea, but they typically don't fallback to GPS when network location is not available, so GrapheneOS doing it for them, fixes the issue at the cost of additional battery use.

Fused location is essentially mixing, yes. On traditional Play Services systems, Play Services provides both APIs (just like they also provide network location). I don't have a full picture of which ROMs support which of the two APIs and to what capacity (i.e. if they require a network location provider present or they can just fallback to GNSS). I know that GrapheneOS has a compatibility feature for the Google API, not sure what's their status on AOSP fused API.

**Comment by alohapersona** [comment]
> OS location requests are never redirected to sandboxed Google Play

Thanks for confirming, so the table is incorrect, as it currently states that "Network location provider" can be Emulated/GNSS **or** Google, when in fact it can't be Google in GrapheneOS. Network-based location from Google can only be used when Google Fused Location Provider is used, so we likely want that as an independent row (as @eylenburg) already suggested.

> Sending real-time location data to a network service is very privacy invasive.

Agree 100%, maybe this should be added as a comment to the table.

---

For clarification, the idea would then to have three rows (instead of current two) that would be more accurate.
Currently there is:
1. Network-based location
2. Network location provider

With the scope of both very unclear.

The idea is to change to 
1. Network-based location (referring to the ability to locate based on wifi and cell towers)
2. Network location provider (referring to providing an implementation for AOSP ["network" location provider](https://developer.android.com/reference/android/location/LocationManager#NETWORK_PROVIDER))
3. Fused location provider (referring to providing an implementation of [Google Play Services' Fused Location Provider](https://developers.google.com/location-context/fused-location-provider/) interface)

As far as I understand, GrapheneOS has support for all of them, no? 1. can be provided through Play Services if installed, 2. is emulated via GNSS, 3. is either GrapheneOS own implementation (using GNSS) or Play Services (supporting both GNSS and network-based location).

**Comment by eylenburg** [comment]
At the moment the two rows have these intentions:
1. In "Features": can the OS find the (approximate) location without GNSS? For example when you're indoors and can't find the satellite. Sounds like this would still be possible on GrapheneOS but through the fused location provider - just the name of the row needs to be changed to something more fitting.
2. In "Degoogling": will the phone connect to Google servers when the (non-GNSS) location is requested by an app (e.g. the example for a weather apps requesting a rough location every hour)? Here, it would be "no" for GrapheneOS, although right now I'm a bit confused whether it should say "no, because the location is always retrieved through GNSS" or "no, unless you decide to install Play Services which can then get the location from Google"
