### ISSUE TITLE
Add more web browser engines

### ISSUE THREAD

**Issue by niutech** [eylenburg/eylenburg.github.io#88]
Could you please add a modern terminal web browser [Chawan](https://sr.ht/~bptato/chawan/) based on its own engine, supporting HTML5/CSS/JS/Markdown, sixel/kitty images and protocols such as: HTTP(S), FTP, Gopher, Gemini, Finger, etc.?

**Comment by eylenburg** [comment]
Thank you, I will do that when I have some time to update that page.

I also received these suggestions via email:

- [chawan](https://sr.ht/~bptato/chawan/): modern terminal web browser with its own web engine supporting multiple protocols and modern web standards

- [Ferus](https://github.com/ferus-web/ferus): a browser engine written in Nim, supporting multiple protocols and modern web standards, based on chawan

- [Vaev](https://github.com/skift-org/skift/tree/main/src/web):  a browser engine built for speed, accuracy, and simplicity, developed by Clem (sleepy-monax) of skiftOS since November 2023.
